language: python
python:
- '2.7'
branches:
  only:
  - qa
env: 
addons:
  postgresql: '9.4'
services:
- postgresql
before_install:
- openssl aes-256-cbc -K $encrypted_dae10395fed2_key -iv $encrypted_dae10395fed2_iv
  -in travis-ci/setenv.sh.enc -out travis-ci/setenv.sh -d
- sudo apt-get -qq update
install:
- pip install -r requirements.txt
- curl -sL https://raw.githubusercontent.com/travis-ci/artifacts/master/install |
  bash
before_script:
- export BOTO_CONFIG=/dev/null
- "./travis-ci/createdb.sh"
- source ./travis-ci/setenv.sh
- python manage.py db upgrade
- python manage.py seed update
script:
- ./tests/run.sh
after_script:
- "./travis-ci/pre_build.sh"
- "./bundle.sh"
- cd ~/build/Appen && artifacts upload
