"""set onhold of batches not null

Revision ID: 103696ef5788
Revises: b670ad93fa73
Create Date: 2016-11-28 10:24:34.917522

"""

# revision identifiers, used by Alembic.
revision = '103696ef5788'
down_revision = 'b670ad93fa73'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(u'batches', 'onhold',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text(u'false'))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(u'batches', 'onhold',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text(u'false'))
    ### end Alembic commands ###
