"""added level 150 tables abnormalusage/batchhistory/customutterancegroupmembers/pages/rawpieces/subtaskmetricerrors/utteranceselectionfilterpieces

Revision ID: 10dfc6064902
Revises: 7b0c1596294
Create Date: 2015-11-30 15:19:58.090599

"""

# revision identifiers, used by Alembic.
revision = '10dfc6064902'
down_revision = '7b0c1596294'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('batchhistory',
    sa.Column('batchid', sa.INTEGER(), nullable=False),
    sa.Column('userid', sa.INTEGER(), nullable=False),
    sa.Column('event', sa.TEXT(), nullable=False),
    sa.Column('when', postgresql.TIMESTAMP(timezone=True), server_default=sa.text(u'now()'), nullable=False),
    sa.ForeignKeyConstraint(['userid'], [u'users.userid'], name=u'batchhistory_userid_fkey'),
    sa.CheckConstraint("event=ANY(ARRAY['assigned','abandoned','submitted','revoked'])"),
    )
    op.create_index('batchhistorybyuserid', 'batchhistory', ['userid'], unique=False)
    op.create_table('pages',
    sa.Column('pageid', sa.INTEGER(), nullable=False),
    sa.Column('batchid', sa.INTEGER(), nullable=False),
    sa.Column('pageindex', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['batchid'], [u'batches.batchid'], name=u'pages_batchid_fkey'),
    sa.PrimaryKeyConstraint(u'pageid', name=op.f('pk_pages')),
    sa.CheckConstraint('pageindex>=0'),
    )
    op.create_index('pages_batchid_key', 'pages', ['batchid', 'pageindex'], unique=True)
    op.create_index('pagesbybatchid', 'pages', ['batchid'], unique=False)
    op.create_table('abnormalusage',
    sa.Column('metricid', sa.INTEGER(), nullable=False),
    sa.Column('tagid', sa.INTEGER(), nullable=True),
    sa.Column('labelid', sa.INTEGER(), nullable=True),
    sa.Column('degree', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['labelid'], [u'labels.labelid'], name=u'abnormalusage_labelid_fkey'),
    sa.ForeignKeyConstraint(['metricid'], [u'subtaskmetrics.metricid'], name=u'abnormalusage_metricid_fkey'),
    sa.ForeignKeyConstraint(['tagid'], [u'tags.tagid'], name=u'abnormalusage_tagid_fkey'),
    sa.CheckConstraint('tagid IS NOT NULL AND labelid IS NULL OR tagid IS NULL AND labelid IS NOT NULL'),
    sa.CheckConstraint('degree <> 0'),
    )
    op.create_index('abnormalusagebymetricid', 'abnormalusage', ['metricid'], unique=False)
    op.create_table('rawpieces',
    sa.Column('rawpieceid', sa.INTEGER(), nullable=False),
    sa.Column('taskid', sa.INTEGER(), nullable=False),
    sa.Column('rawtext', sa.TEXT(), nullable=False),
    sa.Column('assemblycontext', sa.TEXT(), server_default=sa.text(u"''::text"), nullable=False),
    sa.Column('allocationcontext', sa.TEXT(), server_default=sa.text(u"''::text"), nullable=False),
    sa.Column('meta', sa.TEXT(), nullable=True),
    sa.Column('isnew', sa.BOOLEAN(), server_default=sa.text(u'true'), nullable=False),
    sa.Column('hypothesis', sa.TEXT(), nullable=True),
    sa.Column('words', sa.INTEGER(), server_default=sa.text(u'0'), nullable=True),
    sa.Column('groupid', sa.INTEGER(), nullable=True),
    sa.Column('loadid', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['groupid'], [u'postprocessingutterancegroups.groupid'], name=u'rawpieces_groupid_fkey'),
    sa.ForeignKeyConstraint(['taskid', 'loadid'], [u'loads.taskid', u'loads.loadid'], name=op.f('fk_rawpieces_taskid_loads')),
    sa.ForeignKeyConstraint(['taskid'], [u'tasks.taskid'], name=u'rawpieces_taskid_fkey'),
    sa.PrimaryKeyConstraint(u'rawpieceid', name=op.f('pk_rawpieces'))
    )
    op.create_index(op.f('ix_rawpieces_taskid'), 'rawpieces', ['taskid', 'assemblycontext'], unique=True)
    op.create_index('rawpieces_groupid', 'rawpieces', ['groupid'], unique=False)
    op.create_index('rawpieces_loadid', 'rawpieces', ['loadid'], unique=False)
    op.create_index('rawpieces_taskid', 'rawpieces', ['taskid'], unique=False)
    op.create_table('subtaskmetricerrors',
    sa.Column('metricid', sa.INTEGER(), nullable=False),
    sa.Column('errortypeid', sa.INTEGER(), nullable=False),
    sa.Column('occurences', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['errortypeid'], [u'errortypes.errortypeid'], name=u'subtaskmetricerrors_errortypeid_fkey'),
    sa.ForeignKeyConstraint(['metricid'], [u'subtaskmetrics.metricid'], name=u'subtaskmetricerrors_metricid_fkey'),
    sa.PrimaryKeyConstraint(u'metricid', u'errortypeid', name=op.f('pk_subtaskmetricerrors'))
    )
    op.create_index('subtaskmetricerrorsbymetricid', 'subtaskmetricerrors', ['metricid'], unique=False)
    op.create_table('utteranceselectionfilterpieces',
    sa.Column('filterid', sa.INTEGER(), nullable=False),
    sa.Column('pieceindex', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('data', sa.TEXT(), nullable=False),
    sa.ForeignKeyConstraint(['filterid'], [u'utteranceselectionfilters.filterid'], name=u'utteranceselectionfilterpieces_filterid_fkey'),
    sa.PrimaryKeyConstraint(u'filterid', u'pieceindex', name=op.f('pk_utteranceselectionfilterpieces'))
    )
    op.create_table('customutterancegroupmembers',
    sa.Column('groupid', sa.INTEGER(), nullable=False),
    sa.Column('rawpieceid', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['groupid'], [u'customutterancegroups.groupid'], name=u'customutterancegroupmembers_groupid_fkey'),
    sa.ForeignKeyConstraint(['rawpieceid'], [u'rawpieces.rawpieceid'], name=u'customutterancegroupmembers_rawpieceid_fkey'),
    sa.PrimaryKeyConstraint(u'groupid', u'rawpieceid', name=op.f('pk_customutterancegroupmembers'))
    )
    op.create_index('customutterancegroupmember_by_rawpieceid', 'customutterancegroupmembers', ['rawpieceid'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('customutterancegroupmember_by_rawpieceid', table_name='customutterancegroupmembers')
    op.drop_table('customutterancegroupmembers')
    op.drop_table('utteranceselectionfilterpieces')
    op.drop_index('subtaskmetricerrorsbymetricid', table_name='subtaskmetricerrors')
    op.drop_table('subtaskmetricerrors')
    op.drop_index('rawpieces_taskid', table_name='rawpieces')
    op.drop_index('rawpieces_loadid', table_name='rawpieces')
    op.drop_index('rawpieces_groupid', table_name='rawpieces')
    op.drop_index(op.f('ix_rawpieces_taskid'), table_name='rawpieces')
    op.drop_table('rawpieces')
    op.drop_index('abnormalusagebymetricid', table_name='abnormalusage')
    op.drop_table('abnormalusage')
    op.drop_index('pagesbybatchid', table_name='pages')
    op.drop_index('pages_batchid_key', table_name='pages')
    op.drop_table('pages')
    op.drop_index('batchhistorybyuserid', table_name='batchhistory')
    op.drop_table('batchhistory')
    ### end Alembic commands ###
