"""added performance flags

Revision ID: 15d803310916
Revises: cc85d588c99b
Create Date: 2016-09-20 17:06:24.442544

"""

# revision identifiers, used by Alembic.
revision = '15d803310916'
down_revision = 'cc85d588c99b'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audio_collection_performance_flags',
    sa.Column('performance_flag_id', sa.INTEGER(), nullable=False),
    sa.Column('audio_collection_id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.TEXT(), nullable=False),
    sa.Column('severity', sa.TEXT(), nullable=False),
    sa.Column('enabled', sa.BOOLEAN(), server_default='true', nullable=False),
    sa.CheckConstraint(u"severity IN ('Info', 'Warning', 'Severe')"),
    sa.ForeignKeyConstraint(['audio_collection_id'], ['audio_collections.audio_collection_id'], ),
    sa.PrimaryKeyConstraint('performance_flag_id')
    )
    op.create_index('audio_collection_performance_flags_by_audio_collection_id', 'audio_collection_performance_flags', ['audio_collection_id'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('audio_collection_performance_flags_by_audio_collection_id', table_name='audio_collection_performance_flags')
    op.drop_table('audio_collection_performance_flags')
    ### end Alembic commands ###
