"""added level 030 tables labels

Revision ID: 1d1130e793f4
Revises: 3ee81636ccef
Create Date: 2015-11-30 14:10:33.497657

"""

# revision identifiers, used by Alembic.
revision = '1d1130e793f4'
down_revision = '3ee81636ccef'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('labels',
    sa.Column('labelid', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.TEXT(), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('hotkey', sa.CHAR(length=1), nullable=True),
    sa.Column('extract', sa.TEXT(), nullable=False),
    sa.Column('labelgroupid', sa.INTEGER(), nullable=True),
    sa.Column('labelsetid', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['labelgroupid'], [u'labelgroups.labelgroupid'], name=u'labels_labelgroupid_fkey'),
    sa.ForeignKeyConstraint(['labelsetid'], [u'labelsets.labelsetid'], name=u'labels_labelsetid_fkey'),
    sa.PrimaryKeyConstraint(u'labelid', name=op.f('pk_labels')),
    sa.CheckConstraint("hotkey<>' '"),
    )
    op.create_index(op.f('ix_labels_labelgroupid'), 'labels', ['labelgroupid'], unique=False)
    op.create_index('ix_labels_labelsetid_key', 'labels', ['labelsetid', 'extract'], unique=True)
    op.create_index('ix_labels_labelsetid_key1', 'labels', ['labelsetid', 'name'], unique=True)
    op.create_index('ix_labels_labelsetid_key2', 'labels', ['labelsetid', 'hotkey'], unique=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_labels_labelsetid_key2', table_name='labels')
    op.drop_index('ix_labels_labelsetid_key1', table_name='labels')
    op.drop_index('ix_labels_labelsetid_key', table_name='labels')
    op.drop_index(op.f('ix_labels_labelgroupid'), table_name='labels')
    op.drop_table('labels')
    ### end Alembic commands ###
