"""added enabled for labels.

Revision ID: 1fbb7a87c4f3
Revises: 7a0572fe5890
Create Date: 2017-03-16 12:22:26.933553

"""

# revision identifiers, used by Alembic.
revision = '1fbb7a87c4f3'
down_revision = '7a0572fe5890'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'labels', sa.Column('enabled', sa.BOOLEAN(), server_default='TRUE', nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'labels', 'enabled')
    ### end Alembic commands ###
