"""added table for key expansions

Revision ID: 2daf1f8a80ae
Revises: 1664a6671b7a
Create Date: 2016-12-13 10:06:57.175765

"""

# revision identifiers, used by Alembic.
revision = '2daf1f8a80ae'
down_revision = '1664a6671b7a'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('taskkeyexpansions',
    sa.Column('expansionid', sa.INTEGER(), nullable=False),
    sa.Column('taskid', sa.INTEGER(), nullable=False),
    sa.Column('key', sa.CHAR(length=1), nullable=False),
    sa.Column('expansion', sa.TEXT(), nullable=False),
    sa.PrimaryKeyConstraint('expansionid'),
    sa.UniqueConstraint('taskid', 'expansion'),
    sa.ForeignKeyConstraint(['taskid'], ['tasks.taskid'])
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('taskkeyexpansions')
    ### end Alembic commands ###
