"""removed global_id column from users, use appen_id directly as user_id.

Revision ID: 3026502be744
Revises: 910edd9ef9d1
Create Date: 2017-02-14 13:24:21.832254

"""

# revision identifiers, used by Alembic.
revision = '3026502be744'
down_revision = '910edd9ef9d1'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy.schema import Sequence, CreateSequence, DropSequence

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'users', 'global_id')
    op.alter_column(u'users', 'userid', server_default=None)
    op.execute(DropSequence(Sequence('users_userid_seq')))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.execute(CreateSequence(Sequence('users_userid_seq')))
    op.alter_column('users', 'userid', server_default=sa.text("nextval('users_userid_seq'::regclass)"))
    op.add_column(u'users', sa.Column('global_id', sa.INTEGER(), autoincrement=False, nullable=True))
    ### end Alembic commands ###
