"""added global_project_id in tasks table.

Revision ID: 363ea2dfb255
Revises: 15d803310916
Create Date: 2016-09-28 11:17:29.058566

"""

# revision identifiers, used by Alembic.
revision = '363ea2dfb255'
down_revision = '15d803310916'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'tasks', sa.Column('global_project_id', sa.INTEGER(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'tasks', 'global_project_id')
    ### end Alembic commands ###
