"""added level 170 tables pagemembers/payableevents/workentrylabels/workentryerrors

Revision ID: 3bd72e01991e
Revises: 4550f9a3f34c
Create Date: 2015-11-30 15:31:52.969292

"""

# revision identifiers, used by Alembic.
revision = '3bd72e01991e'
down_revision = '4550f9a3f34c'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payableevents',
    sa.Column('eventid', sa.INTEGER(), nullable=False),
    sa.Column('userid', sa.INTEGER(), nullable=False),
    sa.Column('taskid', sa.INTEGER(), nullable=False),
    sa.Column('subtaskid', sa.INTEGER(), nullable=False),
    sa.Column('created', postgresql.TIMESTAMP(timezone=True), server_default=sa.text(u'now()'), nullable=False),
    sa.Column('batchid', sa.INTEGER(), nullable=False),
    sa.Column('pageid', sa.INTEGER(), nullable=False),
    sa.Column('rawpieceid', sa.INTEGER(), nullable=True),
    sa.Column('workentryid', sa.INTEGER(), nullable=True),
    sa.Column('calculatedpaymentid', sa.INTEGER(), nullable=True),
    sa.Column('localconnection', sa.BOOLEAN(), nullable=True),
    sa.Column('ipaddress', postgresql.CIDR(), nullable=True),
    sa.Column('ratio', postgresql.DOUBLE_PRECISION(), server_default=sa.text(u'1.0'), nullable=False),
    sa.ForeignKeyConstraint(['calculatedpaymentid'], [u'calculatedpayments.calculatedpaymentid'], name=u'payableevents_calculatedpaymentid_fkey'),
    sa.ForeignKeyConstraint(['subtaskid'], [u'subtasks.subtaskid'], name=u'payableevents_subtaskid_fkey'),
    sa.ForeignKeyConstraint(['taskid'], [u'tasks.taskid'], name=u'payableevents_taskid_fkey'),
    sa.ForeignKeyConstraint(['userid'], [u'users.userid'], name=u'payableevents_userid_fkey'),
    sa.PrimaryKeyConstraint(u'eventid', name=op.f('pk_payableevents'))
    )
    op.create_index('payableeventsbybatchid', 'payableevents', ['batchid'], unique=False)
    op.create_index('payableeventsbycalculatedpaymentid', 'payableevents', ['calculatedpaymentid'], unique=False)
    op.create_index('payableeventsbypageid', 'payableevents', ['pageid'], unique=False)
    op.create_index('payableeventsbyrawpieceid', 'payableevents', ['rawpieceid'], unique=False)
    op.create_index('payableeventsbysubtaskid', 'payableevents', ['subtaskid'], unique=False)
    op.create_index('payableeventsbytaskid', 'payableevents', ['taskid'], unique=False)
    op.create_index('payableeventsbyuserid', 'payableevents', ['userid'], unique=False)
    op.create_index('payableeventsbyworkentryid', 'payableevents', ['workentryid'], unique=False)
    op.create_table('pagemembers',
    sa.Column('pageid', sa.INTEGER(), nullable=False),
    sa.Column('memberindex', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('rawpieceid', sa.INTEGER(), nullable=True),
    sa.Column('workentryid', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['pageid'], [u'pages.pageid'], name=u'pagemembers_pageid_fkey'),
    sa.ForeignKeyConstraint(['rawpieceid'], [u'rawpieces.rawpieceid'], name=u'pagemembers_rawpieceid_fkey'),
    sa.ForeignKeyConstraint(['workentryid'], [u'workentries.entryid'], name=u'pagemembers_workentryid_fkey'),
    sa.PrimaryKeyConstraint(u'pageid', u'memberindex', name=op.f('pk_pagemembers')),
    sa.CheckConstraint('rawpieceid IS NOT NULL AND workentryid IS NULL OR rawpieceid IS NULL AND workentryid IS NOT NULL'),
    )
    op.create_index('pagememberbyrawpiecid', 'pagemembers', ['rawpieceid'], unique=False)
    op.create_table('workentryerrors',
    sa.Column('entryid', sa.INTEGER(), nullable=False),
    sa.Column('errortypeid', sa.INTEGER(), nullable=False),
    sa.Column('severity', postgresql.DOUBLE_PRECISION(), nullable=False),
    sa.ForeignKeyConstraint(['entryid'], [u'workentries.entryid'], name=u'workentryerrors_entryid_fkey'),
    sa.ForeignKeyConstraint(['errortypeid'], [u'errortypes.errortypeid'], name=u'workentryerrors_errortypeid_fkey'),
    sa.PrimaryKeyConstraint(u'entryid', u'errortypeid', name=op.f('pk_workentryerrors')),
    sa.CheckConstraint('severity>=0 AND severity<=1'),
    )
    op.create_index('workentryerrorsbyentryid', 'workentryerrors', ['entryid'], unique=False)
    op.create_table('workentrylabels',
    sa.Column('entryid', sa.INTEGER(), nullable=False),
    sa.Column('labelid', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['entryid'], [u'workentries.entryid'], name=u'workentrylabels_entryid_fkey'),
    sa.ForeignKeyConstraint(['labelid'], [u'labels.labelid'], name=u'workentrylabels_labelid_fkey'),
    sa.PrimaryKeyConstraint(u'entryid', u'labelid', name=op.f('pk_workentrylabels'))
    )
    op.create_index('workentrylabelsbyentryid', 'workentrylabels', ['entryid'], unique=False)
    op.create_index('workentrylabelsbylabelid', 'workentrylabels', ['labelid'], unique=False)
    op.drop_index('ix_rawpieces_taskid', table_name='rawpieces')
    op.create_index(op.f('ix_rawpieces_taskid'), 'rawpieces', ['taskid', 'assemblycontext'], unique=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rawpieces_taskid'), table_name='rawpieces')
    op.create_index('ix_rawpieces_taskid', 'rawpieces', ['taskid'], unique=False)
    op.drop_index('workentrylabelsbylabelid', table_name='workentrylabels')
    op.drop_index('workentrylabelsbyentryid', table_name='workentrylabels')
    op.drop_table('workentrylabels')
    op.drop_index('workentryerrorsbyentryid', table_name='workentryerrors')
    op.drop_table('workentryerrors')
    op.drop_index('pagememberbyrawpiecid', table_name='pagemembers')
    op.drop_table('pagemembers')
    op.drop_index('payableeventsbyworkentryid', table_name='payableevents')
    op.drop_index('payableeventsbyuserid', table_name='payableevents')
    op.drop_index('payableeventsbytaskid', table_name='payableevents')
    op.drop_index('payableeventsbysubtaskid', table_name='payableevents')
    op.drop_index('payableeventsbyrawpieceid', table_name='payableevents')
    op.drop_index('payableeventsbypageid', table_name='payableevents')
    op.drop_index('payableeventsbycalculatedpaymentid', table_name='payableevents')
    op.drop_index('payableeventsbybatchid', table_name='payableevents')
    op.drop_table('payableevents')
    ### end Alembic commands ###
