"""add countryid in users and hourly_rate in countries

Revision ID: 43396d8ae515
Revises: ed4ac60bc3fb
Create Date: 2017-04-03 09:07:32.376165

"""

# revision identifiers, used by Alembic.
revision = '43396d8ae515'
down_revision = 'ed4ac60bc3fb'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'countries', sa.Column('hourly_rate', postgresql.DOUBLE_PRECISION(), nullable=True))
    op.add_column(u'users', sa.Column('countryid', sa.INTEGER(), nullable=True))
    op.create_foreign_key(None, 'users', 'countries', ['countryid'], ['country_id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column(u'users', 'countryid')
    op.drop_column(u'countries', 'hourly_rate')
    ### end Alembic commands ###
