"""added level 160 tables batchcheckincache/utteranceselectioncache/workentries

Revision ID: 4550f9a3f34c
Revises: 10dfc6064902
Create Date: 2015-11-30 15:24:30.445883

"""

# revision identifiers, used by Alembic.
revision = '4550f9a3f34c'
down_revision = '10dfc6064902'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('batchcheckincache',
    sa.Column('batchid', sa.INTEGER(), nullable=False),
    sa.Column('rawpieceid', sa.INTEGER(), nullable=False),
    sa.Column('result', sa.TEXT(), nullable=False),
    sa.Column('pageid', sa.INTEGER(), nullable=False)
    )
    op.create_index('batchcheckincache_batchid_key', 'batchcheckincache', ['batchid', 'rawpieceid'], unique=True)
    op.create_index('checkindatabybatchid', 'batchcheckincache', ['batchid'], unique=False)
    op.create_index('checkindatabyrawpiecehid', 'batchcheckincache', ['rawpieceid'], unique=False)
    op.create_table('utteranceselectioncache',
    sa.Column('selectionid', sa.INTEGER(), nullable=False),
    sa.Column('rawpieceid', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['rawpieceid'], [u'rawpieces.rawpieceid'], name=u'utteranceselectioncache_rawpieceid_fkey'),
    sa.ForeignKeyConstraint(['selectionid'], [u'utteranceselections.selectionid'], name=u'utteranceselectioncache_selectionid_fkey'),
    sa.PrimaryKeyConstraint(u'selectionid', u'rawpieceid', name=op.f('pk_utteranceselectioncache'))
    )
    op.create_index('idx_utteranceselectioncache_rawpieceid', 'utteranceselectioncache', ['rawpieceid'], unique=False)
    op.create_table('workentries',
    sa.Column('entryid', sa.INTEGER(), nullable=False),
    sa.Column('created', postgresql.TIMESTAMP(), server_default=sa.text(u'now()'), nullable=False),
    sa.Column('result', sa.TEXT(), nullable=True),
    sa.Column('rawpieceid', sa.INTEGER(), nullable=False),
    sa.Column('batchid', sa.INTEGER(), nullable=False),
    sa.Column('taskid', sa.INTEGER(), nullable=False),
    sa.Column('subtaskid', sa.INTEGER(), nullable=False),
    sa.Column('worktypeid', sa.INTEGER(), nullable=False),
    sa.Column('userid', sa.INTEGER(), nullable=False),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.Column('qaeduserid', sa.INTEGER(), nullable=True),
    sa.Column('qaedentryid', sa.INTEGER(), nullable=True),
    sa.Column('pageid', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['rawpieceid'], [u'rawpieces.rawpieceid'], name=u'workentries_rawpieceid_fkey'),
    sa.ForeignKeyConstraint(['subtaskid'], [u'subtasks.subtaskid'], name=u'workentries_subtaskid_fkey'),
    sa.ForeignKeyConstraint(['taskid'], [u'tasks.taskid'], name=u'workentries_taskid_fkey'),
    sa.ForeignKeyConstraint(['userid'], [u'users.userid'], name=u'workentries_userid_fkey'),
    sa.ForeignKeyConstraint(['worktypeid'], [u'worktypes.worktypeid'], name=u'workentries_worktypeid_fkey'),
    sa.PrimaryKeyConstraint(u'entryid', name=op.f('pk_workentries'))
    )
    op.create_index('workentriesbybatchid', 'workentries', ['batchid'], unique=False)
    op.create_index('workentriesbypageid', 'workentries', ['pageid'], unique=False)
    op.create_index('workentriesbyqaedentryid', 'workentries', ['qaedentryid'], unique=False)
    op.create_index('workentriesbyrawpieceid', 'workentries', ['rawpieceid'], unique=False)
    op.create_index('workentriesbysubtaskid', 'workentries', ['subtaskid'], unique=False)
    op.create_index('workentriesbytaskid', 'workentries', ['taskid'], unique=False)
    op.create_index('workentriesbyuserid', 'workentries', ['userid'], unique=False)
    op.drop_index('ix_rawpieces_taskid', table_name='rawpieces')
    op.create_index(op.f('ix_rawpieces_taskid'), 'rawpieces', ['taskid'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rawpieces_taskid'), table_name='rawpieces')
    op.create_index('ix_rawpieces_taskid', 'rawpieces', ['taskid', 'assemblycontext'], unique=True)
    op.drop_index('workentriesbyuserid', table_name='workentries')
    op.drop_index('workentriesbytaskid', table_name='workentries')
    op.drop_index('workentriesbysubtaskid', table_name='workentries')
    op.drop_index('workentriesbyrawpieceid', table_name='workentries')
    op.drop_index('workentriesbyqaedentryid', table_name='workentries')
    op.drop_index('workentriesbypageid', table_name='workentries')
    op.drop_index('workentriesbybatchid', table_name='workentries')
    op.drop_table('workentries')
    op.drop_index('idx_utteranceselectioncache_rawpieceid', table_name='utteranceselectioncache')
    op.drop_table('utteranceselectioncache')
    op.drop_index('checkindatabyrawpiecehid', table_name='batchcheckincache')
    op.drop_index('checkindatabybatchid', table_name='batchcheckincache')
    op.drop_index('batchcheckincache_batchid_key', table_name='batchcheckincache')
    op.drop_table('batchcheckincache')
    ### end Alembic commands ###
