"""added worker payment type in users table

Revision ID: 47413d4bbeae
Revises: 922592ec6793
Create Date: 2017-06-14 12:11:41.732142

"""

# revision identifiers, used by Alembic.
revision = '47413d4bbeae'
down_revision = '922592ec6793'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'users', sa.Column('workerpaymenttype', sa.INTEGER(), server_default=sa.text(u'0'), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'users', 'workerpaymenttype')
    ### end Alembic commands ###
