"""added table for languages and countries

Revision ID: 915facc50d35
Revises: 363ea2dfb255
Create Date: 2016-10-05 23:24:46.018511

"""

# revision identifiers, used by Alembic.
revision = '915facc50d35'
down_revision = '363ea2dfb255'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('countries',
    sa.Column('country_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('iso2', sa.VARCHAR(length=2), nullable=True),
    sa.Column('iso3', sa.VARCHAR(length=3), nullable=False),
    sa.Column('iso_num', sa.INTEGER(), nullable=False),
    sa.Column('internet', sa.VARCHAR(length=3), nullable=True),
    sa.Column('active', sa.BOOLEAN(), server_default=sa.text(u'TRUE'), nullable=False),
    sa.PrimaryKeyConstraint('country_id'),
    sa.UniqueConstraint('internet'),
    sa.UniqueConstraint('iso2'),
    sa.UniqueConstraint('iso3'),
    sa.UniqueConstraint('iso_num'),
    sa.UniqueConstraint('name')
    )
    op.create_table('languages',
    sa.Column('language_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('iso2', sa.VARCHAR(length=2), nullable=True),
    sa.Column('iso3', sa.VARCHAR(length=3), nullable=False),
    sa.Column('active', sa.BOOLEAN(), server_default=sa.text(u'TRUE'), nullable=False),
    sa.Column('ltr', sa.Boolean(), server_default=sa.text(u'TRUE'), nullable=False),
    sa.PrimaryKeyConstraint('language_id'),
    sa.UniqueConstraint('iso2'),
    sa.UniqueConstraint('iso3'),
    sa.UniqueConstraint('name')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('languages')
    op.drop_table('countries')
    ### end Alembic commands ###
