"""added useWorkRate to table subtasks

Revision ID: 9852b73f72aa
Revises: 7eeb62d73fe6
Create Date: 2017-04-03 13:01:27.192557

"""

# revision identifiers, used by Alembic.
revision = '9852b73f72aa'
down_revision = '7eeb62d73fe6'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'subtasks', sa.Column('useworkrate', sa.BOOLEAN(), server_default=sa.text(u'false'), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'subtasks', 'useworkrate')
    ### end Alembic commands ###
