"""empty message

Revision ID: a2c1f3b807f7
Revises: c208eb743044
Create Date: 2016-09-13 14:43:37.532918

"""

# revision identifiers, used by Alembic.
revision = 'a2c1f3b807f7'
down_revision = 'c208eb743044'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(u'corpus_codes', 'requires_cutup', new_column_name='is_scripted')
    op.execute('update corpus_codes set is_scripted = not is_scripted')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(u'corpus_codes', 'is_scripted', new_column_name='requires_cutup')
    op.execute('update corpus_codes set requires_cutup = not requires_cutup')
    ### end Alembic commands ###
