"""empty message

Revision ID: c208eb743044
Revises: 323971271781
Create Date: 2016-09-12 14:30:51.694972

"""

# revision identifiers, used by Alembic.
revision = 'c208eb743044'
down_revision = '323971271781'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'recording_platforms', sa.Column('audio_cutup_config', postgresql.JSONB(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'recording_platforms', 'audio_cutup_config')
    ### end Alembic commands ###
