"""added audio stats types

Revision ID: c9c085ac7898
Revises: d01de4a07b27
Create Date: 2017-07-24 17:03:44.427415

"""

# revision identifiers, used by Alembic.
revision = 'c9c085ac7898'
down_revision = 'd01de4a07b27'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audio_stats_types',
    sa.Column('audio_stats_type_id', sa.Integer(), nullable=False, autoincrement=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('is_default', sa.BOOLEAN(), nullable=False),
    sa.PrimaryKeyConstraint('audio_stats_type_id'),
    sa.UniqueConstraint('key'),
    sa.UniqueConstraint('name')
    )
    op.create_table('recording_platform_audio_stats_types',
    sa.Column('recording_platform_id', sa.Integer(), nullable=False),
    sa.Column('audio_stats_type_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['audio_stats_type_id'], ['audio_stats_types.audio_stats_type_id'], ),
    sa.ForeignKeyConstraint(['recording_platform_id'], ['recording_platforms.recording_platform_id'], ),
    sa.PrimaryKeyConstraint('recording_platform_id', 'audio_stats_type_id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recording_platform_audio_stats_types')
    op.drop_table('audio_stats_types')
    ### end Alembic commands ###
