"""set user id to increment automatically

Revision ID: cc85d588c99b
Revises: d7799ac9b6a7
Create Date: 2016-09-21 13:11:11.149605

"""

# revision identifiers, used by Alembic.
revision = 'cc85d588c99b'
down_revision = 'd7799ac9b6a7'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.schema import Sequence, CreateSequence, DropSequence
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(u'ao_users', 'emailaddress',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column(u'users', 'emailaddress',
               existing_type=sa.TEXT(),
               nullable=False)
    op.execute(CreateSequence(Sequence('users_userid_seq')))
    op.alter_column('users', 'userid', server_default=sa.text("nextval('users_userid_seq'::regclass)"))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'userid', server_default=None)
    op.execute(DropSequence(Sequence('users_userid_seq')))
    op.alter_column(u'users', 'emailaddress',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column(u'ao_users', 'emailaddress',
               existing_type=sa.TEXT(),
               nullable=False)
    ### end Alembic commands ###
