"""added bonus field in subtaskrates

Revision ID: f74888f5f13a
Revises: 9852b73f72aa
Create Date: 2017-04-10 10:56:58.068643

"""

# revision identifiers, used by Alembic.
revision = 'f74888f5f13a'
down_revision = '9852b73f72aa'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'subtaskrates', sa.Column('bonus', postgresql.DOUBLE_PRECISION(), nullable=True))
    op.create_check_constraint('subtaskrates_bonus_check', 'subtaskrates',
        sa.text('bonus > 0'),
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'subtaskrates', 'bonus')
    ### end Alembic commands ###
