"""empty message

Revision ID: f7527fcfb31e
Revises: 286d5016f800
Create Date: 2017-11-09 10:26:43.361039

"""

# revision identifiers, used by Alembic.
revision = 'f7527fcfb31e'
down_revision = '286d5016f800'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('writingscripts',
    sa.Column('script_id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.TEXT(), nullable=True),
    sa.Column('code', sa.VARCHAR(length=4), nullable=False),
    sa.Column('n_code', sa.VARCHAR(length=3), nullable=False),
    sa.PrimaryKeyConstraint('script_id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('n_code'),
    sa.UniqueConstraint('name')
    )
    op.create_table('dialects',
    sa.Column('dialect_id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.TEXT(), nullable=False),
    sa.Column('language_code', sa.CHAR(length=3), nullable=False),
    sa.Column('country_code', sa.CHAR(length=3), nullable=False),
    sa.Column('script_id', sa.INTEGER(), nullable=False),
    sa.Column('ltr', sa.BOOLEAN(), nullable=False),
    sa.Column('romanization_scheme', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['script_id'], ['writingscripts.script_id'], ),
    sa.PrimaryKeyConstraint('dialect_id')
    )
    op.create_table('alphabets',
    sa.Column('alphabet_id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.TEXT(), nullable=False),
    sa.Column('dialect_id', sa.INTEGER(), nullable=False),
    sa.Column('active', sa.BOOLEAN(), server_default=sa.text(u'TRUE'), nullable=False),
    sa.Column('manual_url', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['dialect_id'], ['dialects.dialect_id'], ),
    sa.PrimaryKeyConstraint('alphabet_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('graphemes',
    sa.Column('grapheme_id', sa.INTEGER(), nullable=False),
    sa.Column('key', sa.TEXT(), nullable=False),
    sa.Column('alphabet_id', sa.INTEGER(), nullable=False),
    sa.Column('token', sa.TEXT(), nullable=False),
    sa.Column('orthography', sa.TEXT(), nullable=True),
    sa.Column('romanization', sa.TEXT(), nullable=True),
    sa.Column('sample_word', sa.TEXT(), nullable=True),
    sa.Column('sample_transcription', sa.TEXT(), nullable=True),
    sa.Column('sample_romanization', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['alphabet_id'], ['alphabets.alphabet_id'], ),
    sa.PrimaryKeyConstraint('grapheme_id'),
    sa.UniqueConstraint('alphabet_id', 'key'),
    sa.UniqueConstraint('alphabet_id', 'token')
    )
    op.create_table('rules',
    sa.Column('rule_id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.TEXT(), nullable=False),
    sa.Column('type', sa.TEXT(), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('alphabet_id', sa.INTEGER(), nullable=False),
    sa.CheckConstraint(u"type=ANY(ARRAY['phonology','stress','syllabification','vowelisation'])"),
    sa.ForeignKeyConstraint(['alphabet_id'], ['alphabets.alphabet_id'], ),
    sa.PrimaryKeyConstraint('rule_id'),
    sa.UniqueConstraint('name', 'alphabet_id')
    )
    op.create_table('rule_patterns',
    sa.Column('regex_id', sa.INTEGER(), nullable=False),
    sa.Column('rule_id', sa.INTEGER(), nullable=False),
    sa.Column('search', sa.TEXT(), nullable=False),
    sa.Column('replace', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['rule_id'], ['rules.rule_id'], ),
    sa.PrimaryKeyConstraint('regex_id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rule_patterns')
    op.drop_table('rules')
    op.drop_table('graphemes')
    op.drop_table('alphabets')
    op.drop_table('dialects')
    op.drop_table('writingscripts')
    ### end Alembic commands ###
